version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cat_social_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cat_social
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: